version: '3.8'

services:
  #  robotutor-tech-nginx:
  #    image: nginx:stable-perl
  #    container_name: robotutor-tech-nginx
  #    restart: unless-stopped
  #    volumes:
  #      - ./default.conf:/etc/nginx/conf.d/default.conf
  #    ports:
  #      - 5000:5000
  #    networks:
  #      - robotutor-tech
  #
  #  robotutor-tech-ui:
  #    image: shiviraj/robotutor-tech-ui:latest
  #    container_name: robotutor-tech-ui
  #    restart: unless-stopped
  #    environment:
  #      PORT: 3000
  #    networks:
  #      - robotutor-tech
  #
  #  robotutor-tech-backend:
  #    image: shiviraj/robotutor-tech-backend:latest
  #    container_name: robotutor-tech-backend
  #    restart: unless-stopped
  #    environment:
  #      PORT: 5001
  #      MONGODB_URL: ${WEBSITE_MONGODB_URL}
  #      EMAIL_HOST: ${WEBSITE_EMAIL_HOST}
  #      EMAIL_PORT: ${WEBSITE_EMAIL_PORT}
  #      EMAIL: ${WEBSITE_EMAIL}
  #      PASSWORD: ${WEBSITE_PASSWORD}
  #    networks:
  #      - robotutor-tech
#
  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - robotutor-tech

networks:
  robotutor-tech:
    driver: bridge
