version: '3.8'

services:
  robotutor-tech-nginx:
    image: nginx:stable-perl
    container_name: robotutor-tech-nginx
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5000:5000
    networks:
      - robotutor-tech

  robotutor-tech-ui:
    image: shiviraj/robotutor-tech-ui:latest
    container_name: robotutor-tech-ui
    restart: unless-stopped
    environment:
      PORT: 3000
    networks:
      - robotutor-tech

  robotutor-tech-admin:
    image: shiviraj/robotutor-tech-admin:latest
    container_name: robotutor-tech-admin
    restart: unless-stopped
    environment:
      PORT: 1337
      HOST: 0.0.0.0
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: robotutor
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      JWT_SECRET: ${JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
    ports:
      - '1337:1337'
    networks:
      - robotutor-tech

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: robotutor
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - robotutor-tech

networks:
  robotutor-tech:
    driver: bridge
